/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class audio_rtmp_LibRtmp */

#ifndef _Included_audio_rtmp_LibRtmp
#define _Included_audio_rtmp_LibRtmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     audio_rtmp_LibRtmp
 * Method:    initRtmp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_audio_rtmp_LibRtmp_initRtmp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     audio_rtmp_LibRtmp
 * Method:    sendAudio
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_audio_rtmp_LibRtmp_sendAudio
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     audio_rtmp_LibRtmp
 * Method:    sendAudioSpec
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_audio_rtmp_LibRtmp_sendAudioSpec
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     audio_rtmp_LibRtmp
 * Method:    uninitRtmp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_audio_rtmp_LibRtmp_uninitRtmp
  (JNIEnv *, jobject);

/*
 * Class:     audio_rtmp_LibRtmp
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_audio_rtmp_LibRtmp_setDebug
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
